# Generated by Django 3.2.5 on 2021-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=40)),
                ('details', models.CharField(max_length=3000)),
                ('course_price', models.IntegerField()),
                ('course_duration', models.IntegerField()),
                ('tutor', models.CharField(max_length=50)),
                ('tutor_code', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_code', models.CharField(max_length=10)),
            ],
        ),
    ]
