# Generated by Django 3.2.5 on 2021-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_details',
            field=models.CharField(default='Trainer details are to be filled in this part.', max_length=200),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_field',
            field=models.CharField(default='Programming', max_length=40),
        ),
    ]
