# Generated by Django 3.2.5 on 2021-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorhome', '0002_auto_20210726_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_photo',
            field=models.CharField(default='../static/img/trainers/trainer-1.jpg', max_length=200),
        ),
    ]
