# Generated by Django 3.2.5 on 2021-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorhome', '0003_trainer_trainer_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
