# Generated by Django 3.2.5 on 2021-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorhome', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
